// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'extra-extra-large': string;
  'extra-large': string;
  'extra-small': string;
  'important': string;
  'large': string;
  'medium': string;
  'neutral': string;
  'no-margin': string;
  'small': string;
}
export const cssExports: CssExports;
export default cssExports;
