// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form-group': string;
  'form-group-large': string;
  'largeCheckbox': string;
  'left': string;
}
export const cssExports: CssExports;
export default cssExports;
