// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'controlClose': string;
  'internalNotification': string;
}
export const cssExports: CssExports;
export default cssExports;
